// src/app/Head.tsx

import Head from 'next/head';

const HeadComponent = () => (
  <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
  </Head>
);

export default HeadComponent;
